### PR TITLE
[Feature] Support fromUint8List

### PR DESCRIPTION
**Pull request by yanivshaked**
This provide support for #9

### CODE REVIEW

**Comment by yanivshaked** [comment]
Please review carefully, as I have changed the inner representation from Uint32tList to Uint8tList

**Comment by isoos** [comment]
Two quick questions:
- What is the performance change on a VM app for the different operations? Could you please do a few benchmark? I remember that ~ a year ago the difference was significant, but don't recall the details.
- Would it be possible to abstract away this part of the implementation and support both through e.g. a constructor parameter?

**Comment by yanivshaked** [comment]
- I will send a performance comparison shortly.
- I will check if possible to use a template implementation

**Comment by yanivshaked** [comment]
Regarding performance: All tests show more or less the same performance except for one test: complex bit arrays.

Using Uint32List:
image

Using Uint8List:
image

This specific test runs 3 times slower.
I will check if it's possible to use template for the implementation.

**Comment by yanivshaked** [comment]
> * Would it be possible to abstract away this part of the implementation and support both through e.g. a constructor parameter?

Unfortunately, I don't think it's possible. 
An alternative would be to create two different implementations, one for Uint8tList and one for Uint32tList.

**Comment by yanivshaked** [comment]
@isoos Any thoughts?
It is critical to have support for Uint8tList...

**Comment by yanivshaked** [comment]
I'm closing this PR request for now, will think of an alternative solution.

**Pull request closed without merging**
