### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by happy-san**
Update example.

### CODE REVIEW

**Review by isoos — APPROVED** [review]
thanks :)

**Comment by happy-san** [comment]
@isoos Do I get a cookie?

..actually, just an explanation would do:

Why this instead of
```dart
int _bufferLength32(int length) {
  final hasExtra = (length & 0x1f) != 0;
  return (length >> 5) + (hasExtra ? 1 : 0);
}
```
something like this:
```dart
int _bufferLength32(int length) {
  final hasExtra = (length % 32) != 0;
  return (length ~/ 32) + (hasExtra ? 1 : 0);
}
```

Anything performance related?

**Comment by isoos** [comment]
IIRC bitwise operations (`&` and `>>`) are much faster, but I have benchmarked that a long time ago. Do you have any benchmark that shows otherwise?

**Comment by happy-san** [comment]
>IIRC bitwise operations (& and >>) are much faster

I've known this just as a fact. Maybe I'll try to make a benchmark myself.

Thank you for your response. Have a great weekend!

**Pull request merged**
